spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wiizardy/eureka_repository
          searchPaths: config-dev
          username: wiizardy
          password: yuanyi19930101

server:
  port: 1003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka