server:
  port: 1001
spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: eureka-server